/data/apps/extern/spack_on/gcc/9.3.0/anaconda3/2024.02-1-7cjozusndbeun4sajttdsp5jhe6jqsmt/etc/profile.d/conda.csh: line 1: setenv: command not found
/data/apps/extern/spack_on/gcc/9.3.0/anaconda3/2024.02-1-7cjozusndbeun4sajttdsp5jhe6jqsmt/etc/profile.d/conda.csh: line 2: setenv: command not found
/data/apps/extern/spack_on/gcc/9.3.0/anaconda3/2024.02-1-7cjozusndbeun4sajttdsp5jhe6jqsmt/etc/profile.d/conda.csh: line 3: setenv: command not found
/data/apps/extern/spack_on/gcc/9.3.0/anaconda3/2024.02-1-7cjozusndbeun4sajttdsp5jhe6jqsmt/etc/profile.d/conda.csh: line 4: setenv: command not found
/data/apps/extern/spack_on/gcc/9.3.0/anaconda3/2024.02-1-7cjozusndbeun4sajttdsp5jhe6jqsmt/etc/profile.d/conda.csh: line 32: syntax error near unexpected token `"${1}"'
/data/apps/extern/spack_on/gcc/9.3.0/anaconda3/2024.02-1-7cjozusndbeun4sajttdsp5jhe6jqsmt/etc/profile.d/conda.csh: line 32: `    switch ( "${1}" )'
Epoch 1:   0%|          | 0/1142 [00:00<?, ?it/s]Epoch 1:   0%|          | 0/1142 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/acarbol1/scr4_enalisn1/acarbol1/JSALT_2025/JSALT_2025_dev_int/transformers/train.py", line 151, in <module>
    train_model_manual(dataset_id=0)
  File "/home/acarbol1/scr4_enalisn1/acarbol1/JSALT_2025/JSALT_2025_dev_int/transformers/train.py", line 118, in train_model_manual
    for batch in progress_bar:
  File "/home/acarbol1/.conda/envs/mechanistic_int/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/acarbol1/.conda/envs/mechanistic_int/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 733, in __next__
    data = self._next_data()
  File "/home/acarbol1/.conda/envs/mechanistic_int/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 789, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/acarbol1/.conda/envs/mechanistic_int/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/acarbol1/.conda/envs/mechanistic_int/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/acarbol1/scr4_enalisn1/acarbol1/JSALT_2025/JSALT_2025_dev_int/transformers/train.py", line 64, in __getitem__
    return torch.tensor(self.examples[i], dtype=torch.long)
TypeError: 'NoneType' object cannot be interpreted as an integer
